/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const DcpKpiDashboardHealthyViewLazyImport = createFileRoute(
  '/dcp-kpi-dashboard/healthy-view',
)()
const DcpKpiDashboardHealthyViewIndexLazyImport = createFileRoute(
  '/dcp-kpi-dashboard/healthy-view/',
)()
const DcpKpiDashboardHealthyViewDrilldownLazyImport = createFileRoute(
  '/dcp-kpi-dashboard/healthy-view/drilldown',
)()
const DcpKpiDashboardHealthyViewDrilldownIndexLazyImport = createFileRoute(
  '/dcp-kpi-dashboard/healthy-view/drilldown/',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DcpKpiDashboardHealthyViewLazyRoute =
  DcpKpiDashboardHealthyViewLazyImport.update({
    path: '/dcp-kpi-dashboard/healthy-view',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/dcp-kpi-dashboard/healthy-view.lazy').then((d) => d.Route),
  )

const DcpKpiDashboardHealthyViewIndexLazyRoute =
  DcpKpiDashboardHealthyViewIndexLazyImport.update({
    path: '/',
    getParentRoute: () => DcpKpiDashboardHealthyViewLazyRoute,
  } as any).lazy(() =>
    import('./routes/dcp-kpi-dashboard/healthy-view/index.lazy').then(
      (d) => d.Route,
    ),
  )

const DcpKpiDashboardHealthyViewDrilldownLazyRoute =
  DcpKpiDashboardHealthyViewDrilldownLazyImport.update({
    path: '/drilldown',
    getParentRoute: () => DcpKpiDashboardHealthyViewLazyRoute,
  } as any).lazy(() =>
    import('./routes/dcp-kpi-dashboard/healthy-view/drilldown.lazy').then(
      (d) => d.Route,
    ),
  )

const DcpKpiDashboardHealthyViewDrilldownIndexLazyRoute =
  DcpKpiDashboardHealthyViewDrilldownIndexLazyImport.update({
    path: '/',
    getParentRoute: () => DcpKpiDashboardHealthyViewDrilldownLazyRoute,
  } as any).lazy(() =>
    import('./routes/dcp-kpi-dashboard/healthy-view/drilldown/index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/dcp-kpi-dashboard/healthy-view': {
      id: '/dcp-kpi-dashboard/healthy-view'
      path: '/dcp-kpi-dashboard/healthy-view'
      fullPath: '/dcp-kpi-dashboard/healthy-view'
      preLoaderRoute: typeof DcpKpiDashboardHealthyViewLazyImport
      parentRoute: typeof rootRoute
    }
    '/dcp-kpi-dashboard/healthy-view/drilldown': {
      id: '/dcp-kpi-dashboard/healthy-view/drilldown'
      path: '/drilldown'
      fullPath: '/dcp-kpi-dashboard/healthy-view/drilldown'
      preLoaderRoute: typeof DcpKpiDashboardHealthyViewDrilldownLazyImport
      parentRoute: typeof DcpKpiDashboardHealthyViewLazyImport
    }
    '/dcp-kpi-dashboard/healthy-view/': {
      id: '/dcp-kpi-dashboard/healthy-view/'
      path: '/'
      fullPath: '/dcp-kpi-dashboard/healthy-view/'
      preLoaderRoute: typeof DcpKpiDashboardHealthyViewIndexLazyImport
      parentRoute: typeof DcpKpiDashboardHealthyViewLazyImport
    }
    '/dcp-kpi-dashboard/healthy-view/drilldown/': {
      id: '/dcp-kpi-dashboard/healthy-view/drilldown/'
      path: '/'
      fullPath: '/dcp-kpi-dashboard/healthy-view/drilldown/'
      preLoaderRoute: typeof DcpKpiDashboardHealthyViewDrilldownIndexLazyImport
      parentRoute: typeof DcpKpiDashboardHealthyViewDrilldownLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  DcpKpiDashboardHealthyViewLazyRoute:
    DcpKpiDashboardHealthyViewLazyRoute.addChildren({
      DcpKpiDashboardHealthyViewDrilldownLazyRoute:
        DcpKpiDashboardHealthyViewDrilldownLazyRoute.addChildren({
          DcpKpiDashboardHealthyViewDrilldownIndexLazyRoute,
        }),
      DcpKpiDashboardHealthyViewIndexLazyRoute,
    }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dcp-kpi-dashboard/healthy-view"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/dcp-kpi-dashboard/healthy-view": {
      "filePath": "dcp-kpi-dashboard/healthy-view.lazy.tsx",
      "children": [
        "/dcp-kpi-dashboard/healthy-view/drilldown",
        "/dcp-kpi-dashboard/healthy-view/"
      ]
    },
    "/dcp-kpi-dashboard/healthy-view/drilldown": {
      "filePath": "dcp-kpi-dashboard/healthy-view/drilldown.lazy.tsx",
      "parent": "/dcp-kpi-dashboard/healthy-view",
      "children": [
        "/dcp-kpi-dashboard/healthy-view/drilldown/"
      ]
    },
    "/dcp-kpi-dashboard/healthy-view/": {
      "filePath": "dcp-kpi-dashboard/healthy-view/index.lazy.tsx",
      "parent": "/dcp-kpi-dashboard/healthy-view"
    },
    "/dcp-kpi-dashboard/healthy-view/drilldown/": {
      "filePath": "dcp-kpi-dashboard/healthy-view/drilldown/index.lazy.tsx",
      "parent": "/dcp-kpi-dashboard/healthy-view/drilldown"
    }
  }
}
ROUTE_MANIFEST_END */
